#!/bin/bash
#clear
./Run_HMS_Hold --vid="SampleVideoStitch_3600frames_352288_r1_2" --H=352 --W=288 --rlist="./OrderedFrames_SampleVideoStitch_3600frames_352288_r1_2_downsampled1_5.txt" --qp=24 --mcu=16 --mpd=2 --refa=8 --refs=4 --fps=30 --fsr=6 --nf=300000 --mode=stitch --output_dir="./HMSResults" 


