#!/bin/bash
#clear
f1=../../HMStitching2C/savenpy/rp_640480_VP9_rate10000000_fps24_.dat



echo '----------------------'
./GetRate $f1
python Compare_Plan_V9_Rate_PSNR_VMAF_NoPlot_v1.py --fn1=$f1 --fps=24 --nf=0

