#!/bin/bash
#clear

python GenerateCFG.py --rate=2M
python Distributed_GOP_v1.py --c=./Distributed_GOP_Config.cfg

python GenerateCFG.py --rate=2M
python Distributed_GOP_v1.py --c=./Distributed_GOP_Config.cfg

python GenerateCFG.py --rate=2M
python Distributed_GOP_v1.py --c=./Distributed_GOP_Config.cfg

python GenerateCFG.py --rate=2M
python Distributed_GOP_v1.py --c=./Distributed_GOP_Config.cfg

