#!/bin/bash
# Script that concatenates all the files defined in concat_clips.txt


input_dir="../vid/UCF_c02_g02_clips12/"
splits=3
output_dir=$input_dir$splits"parts/"

python ./cutvid.py --input_dir=$input_dir --output_dir=$output_dir --splits=$splits
