#!/bin/bash
# Script that concatenates all the files defined in concat_clips.txt

output_dir="../vid/"
input_dir="../vid/HD_CIF/"
output_filename="HD_W352_H288_fps4_vid4_r2"
infps=24
outfps=4
W=352 #1920
H=288 #1080
vidd=8000
ctmin=1000
ctmax=1100


python ./concatvid.py --input_dir=$input_dir --output_dir=$output_dir --output_filename=$output_filename --infps=$infps --outfps=$outfps --W=$W --H=$H --vidd=$vidd --ctmin=$ctmin --ctmax=$ctmax
