#!/bin/bash
# Script that concatenates all the files defined in concat_clips.txt

output_dir="../vid/"
input_dir="../vid/UCF_c02_g02_clips12/2parts/"
output_filename="UCF_c02_g02_clips12_2parts"
infps=24
outfps=8
W=320
H=240
vidd=800
ctmin=10
ctmax=12


python ./concatvid.py --input_dir=$input_dir --output_dir=$output_dir --output_filename=$output_filename --infps=$infps --outfps=$outfps --W=$W --H=$H --vidd=$vidd --ctmin=$ctmin --ctmax=$ctmax
