#!/bin/bash
#clear

vid="BosphorusShakeNDryHoneyBee_1920x1080_120fps_420_8bit_YUV_rrc15"
W=1920
H=1080

fps=120

output_dir="../savenpy"
opt=''


#ffmpeg -y -i ../vid/$vid.mp4 -vcodec rawvideo -pix_fmt yuv420p ../vid/$vid.yuv

## Target Bit Rate 
#opt='Test'
rate=6000000;
./Run_VP9_Rate_ver0 --vid=$vid --W=$W --H=$H  --rate=$rate --fps=$fps --output_dir=$output_dir --opt=$opt

rate=7000000;
./Run_VP9_Rate_ver0 --vid=$vid --W=$W --H=$H  --rate=$rate --fps=$fps --output_dir=$output_dir --opt=$opt

rate=8000000;
./Run_VP9_Rate_ver0 --vid=$vid --W=$W --H=$H  --rate=$rate --fps=$fps --output_dir=$output_dir --opt=$opt

rate=4000000;
#./Run_VP9_Rate_ver0 --vid=$vid --W=$W --H=$H  --rate=$rate --fps=$fps --output_dir=$output_dir --opt=$opt

rate=5000000;
#./Run_VP9_Rate_ver0 --vid=$vid --W=$W --H=$H  --rate=$rate --fps=$fps --output_dir=$output_dir --opt=$opt

rate=600000;
#./Run_VP9_Rate_ver0 --vid=$vid --W=$W --H=$H  --rate=$rate --fps=$fps --output_dir=$output_dir --opt=$opt

#rate=9000000;
#./Run_VP9_Rate_ver0 --vid=$vid --W=$W --H=$H  --rate=$rate --fps=$fps --output_dir=$output_dir --opt=$opt

#rate=400000;fps=24;
#./Run_VP9_Rate_ver0 --vid=$vid --W=$W --H=$H  --rate=$rate --fps=$fps --output_dir=$output_dir --opt=$opt

