#!/bin/bash
#clear

vid="Sample1_h1080p_d30_6"
W=1920
H=816
rlist="./OrderedFrames_Sample1_h1080p_d30_6_s352288.txt"
mcu=16
mpd=2
nf=300000
output_dir="../HMSResultsTest"


#Normal 4
qp=20;refa=4;refs=0;fps=30;fsr=30;mode=normal;
./Run_HMS_HoldFixPredictRPS --vid=$vid --W=$W --H=$H --rlist=$rlist --qp=$qp --mcu=$mcu --mpd=$mpd --refa=$refa --refs=$refs --fps=$fps --fsr=$fsr --nf=$nf --mode=$mode --output_dir=$output_dir


